/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {};
declare global {}
// for type re-export
declare global {
	// @ts-ignore
	export type { ContractRouterClient } from "@orpc/contract";
	// @ts-ignore
	export type { JsonifiedClient } from "@orpc/openapi-client";
	// @ts-ignore
	export type { contract } from "~/server/orpc/contracts";
}
