// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api-docs': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api-docs').default>>>>
    }
    '/api-spec.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api-spec.json').default>>>>
    }
    '/api/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/[...]').default>>>>
    }
    '/api/auth/callback/:provider': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/auth/callback/[provider]').default>>>>
    }
    '/api': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/index').default>>>>
    }
    '/rpc/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/rpc/[...]').default>>>>
    }
    '/rpc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/rpc/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}