// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.2_magicast@0.3.5_pinia@3.0.3_typescript@5.8.3_vue@3.5.17_typescript@5.8.3__/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.2_magicast@0.3.5_pinia@3.0.3_typescript@5.8.3_vue@3.5.17_typescript@5.8.3__/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.17.7_@biomejs+biome@2.1.2_@netlify+blobs@9.1.2_@parcel+watcher@2.5.1_@types+node_639a525bd398eaabb93b667a9f677058/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../plugins/authCheck.client")> &
  InjectionType<typeof import("../../plugins/i18n.client")> &
  InjectionType<typeof import("../../plugins/i18n.server")> &
  InjectionType<typeof import("../../plugins/i18nInit.client")> &
  InjectionType<typeof import("../../plugins/orpc")> &
  InjectionType<typeof import("../../plugins/theme.client")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
