packages:
  - webserver
  - cli

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - core-js
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - workerd
