name: Security

on:
  schedule:
    - cron: '0 2 * * 1'  # Run weekly on Monday at 2 AM UTC
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run security audit
        run: pnpm audit --audit-level moderate
      
      - name: Check for known vulnerabilities
        run: |
          VULN_COUNT=$(pnpm audit --json | jq '.vulnerabilities | length' || echo "0")
          echo "Found $VULN_COUNT vulnerabilities"
          if [ "$VULN_COUNT" -gt 0 ]; then
            echo "::warning::Found $VULN_COUNT vulnerabilities"
            pnpm audit --json | jq '.vulnerabilities'
          fi
      
      - name: Check for outdated dependencies
        run: |
          echo "Checking for outdated dependencies..."
          pnpm outdated || echo "Some dependencies are outdated"
      
      - name: License check
        run: |
          echo "Checking licenses..."
          pnpm licenses list || echo "License check completed"

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC
      
      - name: Comment on PR
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Dependency Review Failed**\n\nThis PR introduces dependencies that failed the security review. Please check the logs and resolve any security issues.'
            });