// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/29/2025, 3:51:35 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/sou_kohata/WebstormProjects/zxcv/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sou_kohata/WebstormProjects/zxcv/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sou_kohata/WebstormProjects/zxcv/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sou_kohata/WebstormProjects/zxcv/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sou_kohata/WebstormProjects/zxcv/plugins/**/*.{js,ts,mjs}","/Users/sou_kohata/WebstormProjects/zxcv/composables/**/*.{js,ts,mjs}","/Users/sou_kohata/WebstormProjects/zxcv/utils/**/*.{js,ts,mjs}","/Users/sou_kohata/WebstormProjects/zxcv/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sou_kohata/WebstormProjects/zxcv/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sou_kohata/WebstormProjects/zxcv/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sou_kohata/WebstormProjects/zxcv/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;