# Base configuration
name = "zxcv-backend-and-frontend"
main = "./.output/server/index.mjs"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat","no_nodejs_compat_v2"]


[observability]
enabled = true

# Production configuration (default)
[[d1_databases]]
binding = "DB"
database_name = "zxcv-db"
database_id = "ee2c13b9-0d5b-49ea-9bf4-5a65e2f7ad4e"

[[r2_buckets]]
binding = "R2"
bucket_name = "zxcv"

[[send_email]]
name = "EMAIL_SENDER"

[vars]
JWT_SECRET = "test-jwt-secret"
GOOGLE_CLIENT_ID="test-google-client-id"
GOOGLE_CLIENT_SECRET="test-google-client-secret"
GH_OAUTH_CLIENT_ID="test-gh-oauth-client-id"
GH_OAUTH_CLIENT_SECRET="test-gh-oauth"
JWT_ALGORITHM = "HS256"
JWT_EXPIRES_IN = "7d"
RATE_LIMIT_ANONYMOUS = "100"
RATE_LIMIT_AUTHENTICATED = "1000"
RATE_LIMIT_API_KEY = "5000"
EMAIL_FROM = "noreply+zxcv@prism-project.net"
FRONTEND_URL = "https://zxcv.nanasi-apps.xyz/"
APP_URL = "https://zxcv.nanasi-apps.xyz"
ENVIRONMENT = "production"

# Workers Assets configuration
[assets]
binding = "ASSETS"
directory = ".output/public"

# Staging environment configuration
[env.staging]
name = "zxcv-backend-and-frontend-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "zxcv-staging"
database_id = "e3bce64a-4462-4812-a343-c04c3ba7032a"

[[env.staging.r2_buckets]]
binding = "R2"
bucket_name = "zxcv-staging"

[[env.staging.send_email]]
name = "EMAIL_SENDER"

[env.staging.vars]
JWT_ALGORITHM = "HS256"
JWT_EXPIRES_IN = "7d"
RATE_LIMIT_ANONYMOUS = "100"
RATE_LIMIT_AUTHENTICATED = "1000"
RATE_LIMIT_API_KEY = "5000"
EMAIL_FROM = "noreply+zxcv@prism-project.net"
FRONTEND_URL = "https://zxcv-staging.mattyatea.me/"
APP_URL = "https://zxcv-staging.mattyatea.me"
ENVIRONMENT = "staging"

# Workers Assets configuration for staging
[env.staging.assets]
binding = "ASSETS"
directory = ".output/public"