name: CLI Tests & Release

on:
  push:
    branches: [main, dev]
    paths:
      - 'cli/**'
      - '.github/workflows/cli.yml'
  pull_request:
    branches: [main, dev]
    paths:
      - 'cli/**'
      - '.github/workflows/cli.yml'
  workflow_dispatch:

jobs:
  test-cli:
    name: Test CLI
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.9

      - name: Install CLI dependencies
        run: |
          cd cli
          bun install

      - name: Test CLI
        run: |
          cd cli
          bun test

      - name: Build CLI
        run: |
          cd cli
          bun run build

      - name: Test CLI build
        run: |
          if [ -f "cli/dist/zxcv" ]; then
            echo "✅ CLI build successful"
            # Ensure binary has execute permissions
            chmod +x cli/dist/zxcv
            # Test the binary
            ./cli/dist/zxcv --version || echo "Version command not implemented yet"
          else
            echo "❌ CLI build failed"
            exit 1
          fi

  release-cli:
    name: Release CLI
    runs-on: ubuntu-latest
    needs: test-cli
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.9

      - name: Install CLI dependencies
        run: |
          cd cli
          bun install

      - name: Build CLI for release
        run: |
          cd cli
          bun run build

      - name: Create release
        # Add release logic here if needed
        run: echo "CLI release logic would go here"